import './globals.css'
import { Inter, Bowlby_One } from 'next/font/google'

const bowlby = Bowlby_One({ 
  subsets:['latin'], 
  weight: ['400'],
  variable: '--font-bowlby',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${bowlby.variable}`}>{children}</body>
    </html>
  )
}
